server:
  type: simple
  applicationContextPath: /baragon/v2
  connector:
    type: http
    port: 8080
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ../logs/access.log
        archivedLogFilenamePattern: ../logs/access-%d.log.gz

mesos:
  master: zk://localhost:2181/mesos
  defaultCpus: 1
  defaultMemory: 128
  frameworkName: Baragon
  frameworkId: Baragon
  frameworkFailoverTimeout: 1000000
  useNativeCode: false

zookeeper:
  quorum: localhost:2181
  zkNamespace: baragon
  sessionTimeoutMillis: 60000
  connectTimeoutMillis: 5000
  retryBaseSleepTimeMilliseconds: 1000
  retryMaxTries: 3

ui:
  title: Baragon (docker)
  baseUrl: http://localhost:8080/baragon/v2/ui

logging:
  loggers:
    "com.hubspot.baragon" : TRACE

enableCorsFilter: true
